### ISSUE TITLE
missing rubocop.yml

### ISSUE THREAD

**Issue by djds23** [zachahn/dotfiles#3]
what are your preferred linter rules?

**Comment by zachahn** [comment]
Haha hey! Sorry I missed this! I must have disabled my github notification emails a while back

I actually keep my Rubocop rules in a separate repo: https://github.com/zachahn/the_bath_of_zahn (it's a pun on _The Wrath of Khan_, maybe I should put that in the repo somewhere lol)

Basically it's whatever on the Ruby Style Guide + some custom rules. It's all in the `config/` directory, let me know if you have any questions! It's not perfect... there are some rules I follow that are only in my head.

**Comment by djds23** [comment]
thanks @zachahn!
